### ISSUE TITLE
crashes on load

### ISSUE THREAD

**Issue by majijn** [oneandonlyflexo/nibbler#1]
[crash-2017-12-07_04.06.57-client.txt](https://github.com/oneandonlyflexo/nibbler/files/1537675/crash-2017-12-07_04.06.57-client.txt)
also i tried downgrading the version to the previous one and it says it depends on having botania to work

**Comment by oneandonlyflexo** [comment]
Yeah that first version was borked pretty bad.  Not sure what I'm doing building the mod.  Seems very strange to me.  I'm going to spend some time tonight working on debugging why my mods are crashing when installed like normal mods and working in my dev environment.  My guess is I'm not building the final jar correctly.  Sorry about that, but thanks a lot for the crash report!

**Comment by oneandonlyflexo** [comment]
I'm going to

**Comment by oneandonlyflexo** [comment]
I ended up doing a work around with this issue and just putting the "shared" code directly in the Bark Books mod, which sucks but at least it works now.  I'll still have to figure out what is going on with the interaction between Bark Books and Nibbler.
