### ISSUE TITLE
[1.12.2-0.4] Reject by this mod while using singleplayer

### ISSUE THREAD

**Issue by ghost** [oneandonlyflexo/nibbler#2]
I try load or start new world. I end up get reject by this mod. This shouldn't be happen when i using singleplayer.
[12:13:05] [Server thread/INFO]: Sagez lost connection: Mod rejections [FMLMod:nibbler{0.4}]

[latest.log](https://github.com/oneandonlyflexo/nibbler/files/1580184/latest.log)
[fml-client-latest.log](https://github.com/oneandonlyflexo/nibbler/files/1580186/fml-client-latest.log)

**Comment by oneandonlyflexo** [comment]
Hmm that's an easy fix. Must have just misunderstood the accepted remote version stuff.

**Comment by ghost** [comment]
So.. What do I need to do something with nibbler?

**Comment by oneandonlyflexo** [comment]
Nope. I just uploaded the fix.  There will be a 0.4.1 version soon. You can also revert to 0.3 as a quick work around haha.
