### ISSUE TITLE
loading world crashes

### ISSUE THREAD

**Issue by TimGoll** [oneandonlyflexo/nibbler#3]
your newest version for 1.12.2 stops loading new and old savegames. It stays forever at 0% in the loading screen. I do not have any crash report, because it does not crash. However this is the tested modpack: https://minecraft.curseforge.com/projects/engineers-forest-3

Tested in forge 2582 and 2565

**Comment by oneandonlyflexo** [comment]
Ah I think I know what the problem with this one is.  I uploaded the fixed version as a beta until I tested it, and then never updated the file to release!  0.4.1 fixes this issue and I've marked it as a fully released version.  Sorry for that!
